WIP: Additional metrics
DBD-research-group/UncertainBird-v2 pull request #1
Opened 2024-04-02 06:57 UTC by jonathanschirp

Configuation of additional metrics for multiclass and multilabel experiments.

2024-04-17 07:09 UTC, jonathanschirp commented
Implemented AUPR, AUORC and ECE metrics for Multiclass experiments. The metrics are enabled by default when using module/multiclass.yaml

2024-04-23 14:29 UTC, raphaelschwinger requested changes
@jonathanschirp Thanks for your PR. Good work!
Sorry it took so long to review. Took some effort to get our repo up to date!

I tested it successfully with experiment `local/esc50/efficientnet`!
Pls fix the small suggestion down below and then this gets merged 🔥

2024-04-23 14:29 UTC, raphaelschwinger commented on birdset/modules/metrics/multiclass.py
> +            'F2': torchmetrics.F1Score(
```suggestion
            'F1': torchmetrics.F1Score(
```

2024-04-23 14:29 UTC, raphaelschwinger commented on birdset/modules/multiclass_module.py
> +import torch
@jonathanschirp This is not needed. The `base_module` is for multiclass and we have the `multilabel_module` for multilabel.

2024-04-23 14:29 UTC, raphaelschwinger commented on configs/datamodule/transforms/bird_default_multiclass.yaml
> -n_classes: ${datamodule.dataset.n_classes}
Good catch!

2024-04-26 07:49 UTC, jonathanschirp commented
Should be ready to merge? Should I do that myself or do you want to @raphaelschwinger?

2024-04-26 07:58 UTC, raphaelschwinger commented
@jonathanschirp Thanks! First PR done 🙌  Best practice is that the reviewer merges a PR, i will do that now!

2024-04-26 07:58 UTC, raphaelschwinger approved these changes

2024-04-26 07:58 UTC, merged